### ISSUE TITLE
Candidate/Proposed changes markup

### ISSUE THREAD

**Issue by plehegar** [w3c/specberus#1077]
The T style sheet was adjusted as well:
[[
 *   - .correction for "candidate corrections"       (div, aside, details, section)
 *   - .addition   for "candidate additions"         (div, aside, details, section)
 *   - .correction.proposed for "proposed corrections" (div, aside, details, section)
 *   - .addition.proposed   for "proposed additions"   (div, aside, details, section)
]]
https://www.w3.org/StyleSheets/TR/2016/base.css

We should reflect those CSS classes (without bounding them to specific HTML elements for forward compat) in:
  https://github.com/w3c/specberus/blob/main/lib/rules/sotd/rec-addition.js

This is related to https://github.com/w3c/csswg-drafts/issues/5807

**Comment by plehegar** [comment]
To be clear, unless .correction.proposed and .addition.proposed appear in the document, we should require  only require
the SOTD text: "This document was published by the @@ Working Group as a Recommendation."

**Comment by jennyliang220** [comment]
So the logic is as follows:

Type | candidate corrections | proposed corrections | candidate additions | proposed additions |
----|----|----|----|----
Class|`.correction` | `.correction.proposed` | `.addition` | `.addition.proposed`
Text| **Candidate corrections** are marked in the document.| **Proposed corrections** are marked in the document.| **Candidate additions** are marked in the document.| **Proposed additions** are marked in the document.
sotd|This document was published by the @@ Working Group as a Recommendation.|This document was published by the @@ Working Group as a Recommendation. **It includes proposed corrections.** |This document was published by the @@ Working Group as a Recommendation.|This document was published by the @@ Working Group as a Recommendation. **It includes proposed additions, introducing new features since the previous Recommendation.**

> without bounding them to specific HTML elements for forward compat

@plehegar just to be clear, does it mean the **Text** for HTML element doesn't has to be _'Candidate corrections are marked in the document.'_?

**Comment by jennyliang220** [comment]
@plehegar any idea when will https://github.com/w3c/tr-design/tree/gh-pages/p2020mockup have the mockups? So that specberus can start implementing it.

**Comment by svgeesus** [comment]
This is presumably the cause of https://github.com/w3c/specberus/issues/1312

**Comment by svgeesus** [comment]
@plehegar @jennyliang220 should I just note an open specberus bug and send a publication request anyway?

**Comment by plehegar** [comment]
I added mockups for candidate changes https://github.com/w3c/tr-design/pull/244
