### ISSUE TITLE
Bug in rules: Double negative in missing WG patent policy

### ISSUE THREAD

**Issue by mattgarrish** [w3c/specberus#1257]
[EXPLANATION]

Found [while checking `https://w3c.github.io/epub-specs/epub33/snapshot/epub-rs-33/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fepub-specs%2Fepub33%2Fsnapshot%2Fepub-rs-33%2F&profile=WD&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=).

The error messages says: "Couldn't not determine the patent policy the WG is operating under. Check the WG's charter."

**Comment by jennyliang220** [comment]
Hi @mattgarrish, the document you gave passes Pubrules if you use 'profile: auto', feel free to publish it. 

You're seeing the error 'patent policy...' because there's no default value for 'patent policy' (you have to choose one manually), and we'll change that soon. As well as the double negative. Thanks.

**Comment by mattgarrish** [comment]
> the document you gave passes Pubrules if you use 'profile: auto'

Ah, so that's what caused it. I ran it immediately after testing the EPUB 3.3 document, so it must have picked up the setting. When I reset the page and tried again it ran fine, so I published the documents last night figuring it must have been a bug. Thanks for the clarification, though!
