### ISSUE TITLE
pubrules checker requires link to undated license, causing errors for all bikeshed-generated specs

### ISSUE THREAD

**Issue by dbaron** [w3c/specberus#1418]
The pubrules checker requires that the copyright paragraph link to an undated URL of the relevant license.  However, bikeshed templates for almost all W3C groups generate a dated URL, and this (I think, although it could also be the extra `data-fill-with="copyright"` attribute) causes an error in the pubrules checker.  See, for example, [the errors for the latest published css-values-4](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FWD-css-values-4-20211016%2F&profile=WD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020).

It seems like it should at least be allowed, if not required, to use the dated URL to the license ([document license](https://www.w3.org/Consortium/Legal/2015/doc-license), [software and document license](https://www.w3.org/Consortium/Legal/2015/copyright-software-and-document)) rather than the undated ones ([document license](https://www.w3.org/Consortium/Legal/copyright-documents), [software and document license](https://www.w3.org/Consortium/Legal/copyright-software)) currently required.

(Even if this change isn't accepted, it would be good to allow the [undated url with a clearer name](https://www.w3.org/Consortium/Legal/copyright-software-and-document) for the latter license.)

cc @tabatkins

**Comment by dbaron** [comment]
(I'd note that at the time I filed this, I didn't realize that there was a major update to the rules that had taken place in the past week.  That said, I am a little surprised that the requirement changed to require an undated license link.)

**Comment by tabatkins** [comment]
Importantly, where are these changes documented/announced? From that pubrules link, it looks like a *lot* of things have changed in ways that'll block publication of any Bikeshedded documents right now.

**Comment by jennyliang220** [comment]
Hi @dbaron, 'https://www.w3.org/Consortium/Legal/copyright-software' is supported and shouldn't cause error.

The **copyright** error for the [the latest published css-values-4](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2021%2FWD-css-values-4-20211016%2F&profile=WD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2020) is:

![ error message: Could not get the document license from the API. Please make sure this group has a current charter associated with at least one document license.](https://user-images.githubusercontent.com/8498677/141050951-51f7e1b8-9e09-4b3a-97cf-6f09552973ea.png)

It's mainly because the new Pubrules choose the current charter using the DATE a document is published. For Process 2021, **W3C Working Draft, 16 October 2021** should be in `<p id="w3c-state">` element. 

See error message of the same document: 
<img width="812" alt="Screen Shot 2021-11-10 at 12 38 58 PM" src="https://user-images.githubusercontent.com/8498677/141050806-53a09c81-8bd5-4071-8e4e-2931508ac35c.png">

Documents published before will not pass the Pubrules check. please use the new bikeshed version which fully implements Process2021 requirements.

**Comment by jennyliang220** [comment]
> Importantly, where are these changes documented/announced? From that pubrules link, it looks like a _lot_ of things have changed in ways that'll block publication of any Bikeshedded documents right now.

Hi @tabatkins , the base document Pubrules are developed on is the P2021mockups [here in w3c/tr-design](https://github.com/w3c/tr-design/tree/gh-pages/p2021mockup). Pubrules didn't record the 'changes', but you can see the description in [Publication rules document (e.g. for copyright)](https://www.w3.org/pubrules/doc/rules/?profile=FPWD#copyright) and [for elements like `W3C Working Draft, 16 October 2021`](https://www.w3.org/pubrules/doc/rules/?profile=FPWD#dateState)
