### ISSUE TITLE
New copyright form

### ISSUE THREAD

**Issue by darobin** [w3c/specberus#145]
New rules are in effect (we are at the beginning of a one-month transition period) during which "All Rights Reserved" is no longer part of the copyright string. The old pubrules suggests a copyright string without that phrase (but then fails to validate without it), so that people are already using it (ReSpec will stop generating it with the next release). Specberus needs to update to match.

**Comment by astorije** [comment]
Hey @darobin, how do you see these transition periods applied, in general?

I mean, right now we need to allow both, and in one month we need to disallow the old form. Should we have a date check: "If before [that date], accept both, otherwise accept only the new form"? And if so, should we get rid of this after [that date]? On one hand, leaving it is synonym of dead code, but on the other hand, it will keep Specberus happy when checking an old document in the future, which can be useful.

**Comment by darobin** [comment]
I don't know man, transitions like that are painful :)

It's true that the best option is to check the date, it ought to be doable relatively easily. And maybe include a comment that says something like "if this is 2017 or later, drop this".

**Comment by astorije** [comment]
Or since we are in early stage, we could choose t support only the new version.

That would work well because people using the system are likely to switch to the new copyright as well, but I am more concerned about how to handle these situations after that. We'll always have transition periods that are a pain to deal with and I don't know how to best handle these cases.

**Comment by darobin** [comment]
I'm fine with just supporting the new version, but I don't think it's particularly hard to support the old too.

In the future, it would be great if such transitions were not announced **before** a bug has been opened here and given a chance to be addressed; at the very least.

**Comment by astorije** [comment]
I'm not saying it's hard, I'm saying that things like this will happen often, and even more and more as the process is now updated every year. It would be nice to find a nice way to maintain old and new requirements without having ugly dead code. Does that make sense?

Regarding announcement, I was surprised too but this is a different story, and clearly not the one you should be telling that...

**Comment by mikewest** [comment]
Is this bug causing the copyright failure when parsing https://w3c.github.io/webappsec/specs/CSP2/published/2015-02-CR.html? The copyright text is copy/pasted directly from the old pubchecker. It would be nice if it was supported. :)

**Comment by astorije** [comment]
Hi @mikewest,
Indeed, the copyright statement checked by Specberus is not up-to-date. It will be fixed someday soon, once we figure out how to do that efficiently.

**Comment by astorije** [comment]
All, I am on this one, I will send a PR as soon as possible.

**Comment by astorije** [comment]
Boum, see #151.
