### ISSUE TITLE
CR end regex uncertainty

### ISSUE THREAD

**Issue by darobin** [w3c/specberus#146]
The regex that looks for the CR end date seems dodgy to me: `"no earlier than " + sr.dateRegexStrNonCapturing + "\\."`

I'm not sure that that is a canonical rule; last I checked all that we could be sure of was the date, not a specific sentence form (even if the above matches what ReSpec produces). Is this requirement documented? If not, we should fall back to something that matches expected productions (or document the rule properly).

**Comment by mikewest** [comment]
The document at https://w3c.github.io/webappsec/specs/CSP2/published/2015-02-CR.html is failing the CR end-date check because of this bug. It seems reasonable to be a little less strict with the parsing, as I don't think there's anything objectively wrong with the text in that document. :)

See details at http://www.w3.org/2014/10/pubrules/?url=https%3A%2F%2Fw3c.github.io%2Fwebappsec%2Fspecs%2FCSP2%2Fpublished%2F2015-02-CR.html&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&patentPolicy=pp2004&processDocument=2014

**Comment by tripu** [comment]
Yet another manifestation of [The Pubrules Conundrum](https://github.com/w3c/specberus/issues/130#issuecomment-69293796). @mikewest's comment makes a lot of sense here, and in an infinite number of other places in documents: either we impose rigid copy everywhere on specs, maintain long and extremely flexible regexes to cope with every conceivable wording, or make AI a reality&hellip; this issue isn't going away.

Not to dismiss this particular issue&nbsp;&mdash;&nbsp;I agree we should address it. Just a concerned reminder to everyone involved that we still have to work out a consistent answer for this kind of requests, of which we can only expect more and more in the future :)

**Comment by mikewest** [comment]
I'd actually be fine with strict rules if there was an accessible enumeration of them lying around somewhere. Or boilerplate that you explicitly require folks to copy/paste. Otherwise it's just difficult to understand what words we need to use in what sequence in order to make the system happy. :)

**Comment by deniak** [comment]
#360 should fix the issue
