### ISSUE TITLE
Date format detection is too strict

### ISSUE THREAD

**Issue by astorije** [w3c/specberus#178]
@mikewest [just reported](https://github.com/w3c/echidna/issues/142) a date format detection issue. The URL that can be found [here](http://w3c.github.io/webappsec/specs/upgrade/published/WD.html#biblio-nyt-https) is a false positive.

Per #88, I thought that we would enforce this rule for the SOTD only. Making it apply on the SOTD only would solve @mikewest's problem here as a quick fix.
On the long term, in theory, we'd need to make sure that URLs are not treated as such (by either discarding the checks for URL-like strings, or maybe by simply making sure that there is a whitespace before the string?). In practice, I don't think we will ever have a URL in the SOTD (I mean, not a link of course, but an actual URL-like string) but I could be wrong.

**Comment by mikewest** [comment]
Friendly ping! :)

I still can't use Echidna to publish this specification because of this bug. I suppose I could entity-encode the URL to work around the issue, but I'd prefer not to do that if this will end up on someone's queue shortly. Any chance of that happening? :)

**Comment by tripu** [comment]
PR #119 checks possible dates within these segments of the document:

```js
var boilerplateSections = [
    sr.$('div.head'),
,   sr.$("h2[name='abstract'], h2#abstract, h2[name='status'], h2#status-of-this-document").parent()
]
```

In the case of this particular document, it assumes that `<h2 id="abstract">` is a child of some `<section>`, not of `<body>`. (See for example how `<h2 id="h-abstract">` is contained in a `<section>` element in [`http://www.w3.org/TR/2015/WD-appmanifest-20150407/`](http://www.w3.org/TR/2015/WD-appmanifest-20150407/)). Because of that, it ends up (wrongly) checking *all* dates in the body of the document.

I don't recognise my style in [that new rule](https://github.com/w3c/specberus/commit/0afa4c6ee53177f231085ce0af9609bae767d6e1#diff-e1acdc666aab46bc3558ff79e65ed820), so I suspect I copied part of the logic (sections, regex's) from another rule&hellip;

I have two related questions. Can you help?
* What would be then the right way to identify those &ldquo;boilerplate sections&rdquo;?
* What IDs, classes, names do we enforce in those boilerplate sections? I'm asking because that published WD I mentioned above, for example, doesn't have a `<h2 id="abstract">`, but a `<h2 id="h-abstract">` instead&hellip; This heuristic rule wouldn't find that boilerplate section on that document.

**Comment by mikewest** [comment]
1. The value of the check isn't terribly clear to me. Isn't YYYY/MM/DD a reasonable date format?

2. Skipping URLs seems like a good thing to do for any and all style checks; we can't and shouldn't change URLs, regardless of what we'd like them to be.

In any event, I can certainly put the abstract and SotD into a `<section>` for WebAppSec documents if that would help. I don't have strong feelings about the current markup style, but it is what Bikeshed produces at the moment, so it's likely somewhat widespread, particularly in the CSSWG.

+@tabatkins for other Bikeshedders (and opinions, I suppose :) ).

**Comment by tabatkins** [comment]
Yeah, that's entirely up to the header/footer files for a given group, but all CSSWG specs will have this same issue.

It looks like the section-detection is just wrong.  If it wants to check everything in the "status" section, it needs to scan forward until it finds a heading of equal or higher rank, or sees its closest ancestor sectioning element end.  That's how sections are defined.

**Comment by tripu** [comment]
@mikewest:

1. I'm afraid so: [*&ldquo;5.3. [In the document status section] all dates must have the form DD Month YYYY. A leading zero in the day is optional&rdquo;*](http://www.w3.org/2005/07/pubrules?year=2015&uimode=filter&filter=Filter+pubrules&filterValues=form&docstatus=ord-wd-tr&patpol=w3c&rectrack=yes&normative=yes&procrev=2014&prevrec=none#docreqs). The regex we're using is `/[0123]?\d\ (jan|january|feb|february|mar|march|apr|april|may|jun|june|jul|july|aug|august|sep|september|oct|october|nov|november|dec|december)\ \d{4}/i`
2. I think you are right; skipping URLs seems a sensible idea. I'll implement that change, and hopefully it'll be all that your spec needs to pass this rule.

Regardless of that, there is the general issue identifying boilerplate sections, that you and @tabatkins brought up&hellip; I'll discuss with the team, because I'm unsure how many different cases we can find here.

**Comment by tabatkins** [comment]
There's only two cases; "sections" are well-defined in HTML.  Explicit sectioning elements (including `<body>`) create explicit sections, according to nesting.  The first heading in an explicit section is the heading for that section; further headings in an explicit section create implicit sections, nested according to relative heading level.  (Note that the sections created by sectioning elements are *always* nested directly underneath the section created by their nearest ancestor sectioning element; you can't nest an explicit section inside of an implicit section, as it'll "jump out" and attach itself to the first explicit section it can find.)

So to be a little more precise than I was before, the operation is:

1. Find the SotD heading.  See if it's the heading for an explicit section: walk ancestors to find nearest sectioning ancestor, then walk elements between ancestor and heading (in document order) to see if there's another heading element.  If you find one, this is an implicit section; if you don't, this is an explicit section.  (You can probably simplify this and just find the first sectioning ancestor; if it's `<body>`, it's an implicit section.)

2. If it's an implicit section, walk forward in document order until you either find a sectioning element or or a heading of equal or higher rank.  All elements between the SotD heading and the element you stopped at are part of the implicit section.

3. If it's an explicit section, you've already got the right container.

**Comment by darobin** [comment]
The code for SotD sectioning can be found here: https://github.com/w3c/specberus/blob/master/lib/validator.js#L178

It takes shortcuts compared to the HTML outline algorithm, but I believe they are essentially correct given the constraints we know on documents. At least that's my pre-coffee reading.

What it does is find the `h2` for SotD. Then it goes to its parent, and slurps up all of its parent's children that are after that `h2` and before any following `h2` (stopping happily if the SotD `h2` is in a container).

@tripu I don't understand why PR #119 checks for anything outside of that section. There is nothing in pubrules that I can see that requires checking the abstract, and those selectors are effectively wrong. The dates should just be checked against the content of what `getSotDSection()` returns.
