### ISSUE TITLE
Support for copyright exceptions

### ISSUE THREAD

**Issue by dontcallmedom** [w3c/specberus#187]
There a a (arguably somewhat limited) number of specs that use a different copyright statement from the one blessed by pubrules, and these exceptions have been approved by the power that be.

At the moment, specberus reject these exceptions; to make these document echidna-publishable, it'd be great if they could be blessed by specberus too.

I have two specific use cases for my group:

* http://w3c.github.io/webrtc-pc/
* http://w3c.github.io/mediacapture-main/getusermedia.html

**Comment by darobin** [comment]
I agree that that would be useful, but how do you propose to implement it? Just writing down some thoughts here.

We could make a specific option for Specberus to ignore copyright errors. That's the simplest to implement, but there is a risk that we could start adding a lot of exceptions which would be unpleasant to manage.

We could take it one notch up and allow Specberus to receive a list of errors to ignore (using the key names for errors). The code would be relatively simple, the UI a bit more painful.

For both of the above Echidna would need a way of being informed that an exception has been granted for a document, and transmit that information to Specberus. I'm guessing that would be registered with the token.

Finally, there's the option of addressing this in Echidna alone. Echidna knows (or can know) which specific errors it is getting from Specberus. It could, on its own, decide to ignore some of them.

**Comment by tripu** [comment]
I fear that we'll implement different kinds of flexible mechanisms to introduce exceptions in many aspects of specs (not only the copyright statement), and that that will be prone to errors and make the system more difficult to maintain and update.

@dontcallmedom, these are exceptions in the sense that only those two specs are allowed to be published with that copyright statement, right?

@darobin's idea about muting specific error messages for specific tokens sounds good in principle. My main concern is that ignoring copyright error messages will not just allow those editors to use that special statement&nbsp;&mdash;&nbsp;it will effectively let them to use *any* copyright statement&nbsp;&mdash;&nbsp;or none at all! This may be an issue whenever we ignore on purpose any error message from Specberus, incidentally. So the &ldquo;exceptions system&rdquo; should be smarter than that: instead of saying &ldquo;for spec S, just ignore any error messages about X&rdquo; we should be able to say &ldquo;for spec S, instead of checking X1, check X2&rdquo;. In other words, overwriting entire rules in Specberus, per individual spec/token&hellip;

Is it as complex as I'm painting it here?

**Comment by plehegar** [comment]
@dontcallmedom note that we no longer use ther terms "All Rights Reserved." in copyright statements btw

**Comment by deniak** [comment]
See #208

**Comment by dontcallmedom** [comment]
I see that #208 got closed; does that mean that copyright exceptions are now doable? Was this documented / announced somewhere?

**Comment by deniak** [comment]
@dontcallmedom that feature is not deployed yet. We are working on it and it should be available soon. We'll also describe how someone can request an exception (eg. @plehegar submitted the MR #272 for a CSS error). All these exceptions are listed in [`exceptions.json`](https://github.com/w3c/specberus/blob/master/lib/exceptions.json).

**Comment by tripu** [comment]
@dontcallmedom, exception support was announced [during the break-out session of TPAC](https://www.w3.org/wiki/TPAC2015/session-echidna) (yes; I do realise that might not have reached every corner of the galaxy :) and is [documented on the Echidna wiki](https://github.com/w3c/echidna/wiki/Exceptions) (@deniak and others: feel free to complement that information).

**Comment by dontcallmedom** [comment]
@tripu thanks for the link! I think new features on specberus/echidna could usefully be announced more broadly and systematically, e.g. on spec-prod

**Comment by dontcallmedom** [comment]
meanwhile, I think that issue can be closed

**Comment by tripu** [comment]
(For the record, announcement of exceptions and other recent changes: [`lists.w3.org/Archives/Public/spec-prod/2015OctDec/0067`](https://lists.w3.org/Archives/Public/spec-prod/2015OctDec/0067.html))
