### ISSUE TITLE
Reproduce documentation from pubrules

### ISSUE THREAD

**Issue by darobin** [w3c/specberus#25]
Notably for transitions and errors. Import documentation to the repository so that it's easier to keep in sync.

**Comment by tripu** [comment]
#160 set the basis for this: we have now in this repo all descriptions for all rules from the old pubrules checker ([`lib/rules.json`](https://github.com/w3c/specberus/blob/master/lib/rules.json); it's a bad filename). The mechanism to render those descriptions on the web UI is in place too.

This issue isn't solved though, because matching Specberus rules to the corresponding paragraphs from the old pubrules is, AFAIK, a manual task. We still need to write most selectors in [`l10n-selectors.js`](https://github.com/w3c/specberus/blob/master/lib/l10n-selectors.js).

**Comment by tripu** [comment]
Solved with #355 and a bunch of other related changes (some of them mentioned above).
