### ISSUE TITLE
[feature request] HTML4 support

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#259]
From [Bert's whishlist](https://lists.w3.org/Archives/Public/public-pubrules-comments/2015Sep/0000.html).

**Comment by astorije** [comment]
If memory serves, we explicitly wanted to deny HTML4 support to encourage editors to move over HTML5, which seems more than reasonable to me...

**Comment by deniak** [comment]
+1 @astorije

**Comment by plehegar** [comment]
Indeed. I can't think of a compelling reason to support HTML4 at this point. I realize this might be a bit of a pain for old tools but it simplifies Echidna not to have to deal with the old html validator.

**Comment by sideshowbarker** [comment]
Yeah, unless Bert has a compelling explanation about the value of HTML 4 support (whatever that means), we should definitely not support it.

The current W3C HTML Checker at https://validator.w3.org/nu/ by design doesn't support versioned HTML checking at allー it's an HTML checker, not an HTML5 validator, nor any other kind of validator. "Validation" is  legacy concept with a history in DTDs and SGML.

Dispensing with versioned doctypes means also dispensing with versioned checkers.

If somebody wants for some reason to check their docs on their own against the HTML 4 DTD on their own, using the legacy markup validator.

But that should not resolve them from responsibility to ensure that our current W3C HTML Checker finds no errors in their documents.

**Comment by tripu** [comment]
There seems to be consensus here.
