### ISSUE TITLE
Specberus reload the page by itself after a few minutes

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#479]
How to reproduce:
- load https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2016%2FCR-mixed-content-20160802%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004 
- wait a min or two and specberus will run again

**Comment by deniak** [comment]
I suspect a configuration issue with the websockets and our proxy.

**Comment by deniak** [comment]
The problem came from the process manager we use (https://github.com/Unitech/pm2) and more precisely, the cluster mode. We used to have 2 instances of Specberus and that was causing an [issue with the sessions](https://github.com/Unitech/pm2/issues/389). Fixed by having only one instance for the moment.

**Comment by tripu** [comment]
Congrats for finding this one, @deniak!

I see people report having this fixed by
* restricting transport protocols to [`websocket`](https://github.com/Unitech/PM2/issues/637#issuecomment-98585907) or to [`websocket` and `polling`](https://github.com/Unitech/PM2/issues/637#issuecomment-215915328), and
* [replacing the default adapter](http://socket.io/docs/server-api/#server#adapter(v:adapter):server) with [Redis](https://github.com/socketio/socket.io-redis).

We shall try that, if we don't want to lose the benefits of having multiple instances in production.

I leave these links here for when we do!
