### ISSUE TITLE
Bug in rules: Incorrectly Reports Status Section Missing

### ISSUE THREAD

**Issue by skynavga** [w3c/specberus#535]
Document contains a "Status of this Document" section, but specrebus incorrectly reports that it is missing. Please fix ASAP or let me know a work around.

Found [while checking `https://rawgit.com/w3c/ttml2/ttml2-WD-20161116/spec/ttml2.html`](https://www.w3.org/pubrules/?url=https%3A%2F%2Frawgit.com%2Fw3c%2Fttml2%2Fttml2-WD-20161116%2Fspec%2Fttml2.html&profile=WD-Echidna&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=true&patentPolicy=pp2004).

**Comment by tripu** [comment]
@skynavga, I'm sorry about that. I'm afraid the problem is that the error description is not accurate.

The hyperlink to `https://www.w3.org/TR/` and the plain-text mention [should both be HTTPS](https://www.w3.org/pubrules/doc/rules/?profile=WD#boilerplateTRDoc) now.

I'll fix that error message. In the meantime, I suspect you only have to correct that for the spec to pass.
