### ISSUE TITLE
Bug in rule “headers.dl”: Text of test that compare previous version and latest published version is misleading

### ISSUE THREAD

**Issue by vivienlacourba** [w3c/specberus#620]
When previous version and latest published version do not match pubrules returns an error indicating:
> Error: Could not retrieve URI for previous version or for latest version.

But that message is misleading (as the checker itself found the links as indicated in its metadata view).

The error message should be explicit about what is being tested eg _"the previous version does not match the latest published version"_.

Found [while checking `https://www.w3.org/TR/2017/WD-using-aria-20170504/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FWD-using-aria-20170504%2F&profile=WD&validation=simple-validation&noRecTrack=true&informativeOnly=true&echidnaReady=false&patentPolicy=pp2004).

Related IRC discussion with @tripu:
```
<vivien> tripu, https://www.w3.org/TR/2017/WD-using-aria-20170504/,pubrules
<vivien> "Could not retrieve URI for previous version or for latest version."
<vivien> do you know why ?
<vivien> this WD uses a new shortname
<vivien> but the metadata are ok https://www.w3.org/pubrules/api/metadata?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2017%2FWD-using-aria-20170504%2F
...
<tripu> about the first issue, vivien: https://www.w3.org/TR/using-aria/ ("latest") does not exist
<tripu> (the error is not very descriptive, but that's the root of the problem)
<vivien> tripu, ok (normal as it is a new shortname)
<tripu> looking at the code, I don't think we allow that to happen in pubrules
<vivien> I guess the checker could be smarter as if I look at the metadata it found all the relevant bits (new shortname in latestVersion, old one in previousVersion/sameWorkAs)
<tripu> that particular check doesn't care about shortnames, it just makes sure that both "previous" and "latest" are defined, and that the retrieve the same doc
<tripu> does it make sense?
<vivien> ok I understand the test. I think the name of that test should be updated to match what you described
<tripu> agreed
<vivien> ie: "the previous version does not match the latest published version"
```

**Comment by jennyliang220** [comment]
Before #638 , the reason @vivienlacourba sees this error (Error: Could not retrieve URI...) is because before publication, new shortlink doesn't exist and cannot be retrieved. So the error message was correct?

Currently if a shortname-change are detected, specberus will not check if `PreviousVersion` and `latestPublishedVersion` are the same document, it just quit the check. See this commit which add this feature: https://github.com/w3c/specberus/pull/638/files.

@deniak @vivienlacourba can we close this issue, or add new feature to **retrieve shortlink before shortname change, to see if the two document matches**?

**Comment by deniak** [comment]
yes, I believe the error was related to shortname changes. This has been fixed since then so +1 to close it

**Comment by vivienlacourba** [comment]
@jennyliang220 yes it can be closed. Thanks!
