### ISSUE TITLE
how would I check a spec?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/specberus#705]
Would be great to have simple (think Marcos) steps to check, for instance, [Payment Request](https://w3c.github.io/payment-request/) spec's PubRule conformance. That is:

 * npm install 
 * pass in "https://w3c.github.io/payment-request/" (or do I need to generate it?)
 * get specberus to error in the console if non-conforming, etc.

**Comment by marcoscaceres** [comment]
Speaking with @tidoust, we need to figure out what the end-point to send stuff to is.

**Comment by tidoust** [comment]
OK, found the endpoint for ourt install `https://www.w3.org/pubrules/api/`. The documentation is not extraordinarily clear about that though.

I understand the tool could be deployed elsewhere, but since `https://www.w3.org/pubrules/` links to the README for the REST API, it would be good to have the endpoint appear explicitly there!

**Comment by tripu** [comment]
Correct.

Marcos, we'll even save you the `npm install`! 🙄

Example: [`https://www.w3.org/pubrules/api/validate?url=https://www.w3.org/TR/payment-handler/&profile=auto`](https://www.w3.org/pubrules/api/validate?url=https://www.w3.org/TR/payment-handler/&profile=auto), which obviously you can `curl` from the command line.
The result is [in JSON](https://github.com/w3c/specberus#return-values).
You can use that instance (`w3.org/pubrules`), or your own.

Nowadays, Pubrules is almost exclusively used either via [its web UI](https://www.w3.org/pubrules/) (by humans) or as an npm module (by Echidna, the automatic publication system). Because of that, we haven't been maintaining nor documenting much the 3<sup>rd</sup> interaface: the REST API. But it's there.

Documentation of the API is [on the README](https://github.com/w3c/specberus#5-rest-api), yes; parameters accepted [are the same as the JS (npm) interface](https://github.com/w3c/specberus#validateoptions).

I'll leave this open as a reminder to include a link to the API, thanks!

**Comment by marcoscaceres** [comment]
@tripu - Ok, but now imagine I'm editing a spec locally (either "file:///" or "http://localhost:8000" or whatever), and I want to be checking validity as a I go. Could I POST a payload to the API? The payload would be a HTML document, and I want that content to be checked for validity.

**Comment by tripu** [comment]
@marcoscaceres: no payload allowed, but [apart from param `url` you can use `file`](https://github.com/w3c/specberus#5-rest-api).

```bash
$ cd specberus    # assuming there's a clone of Specberus there
$ npm i
$ npm start 3000 &
$ curl 'http://localhost:3000/api/validate?file=/foo/bar/spec.html&profile=auto'    # assuming your spec is there
```

Yes, you need to run a local instance of Specberus&hellip; What `file` does is avoiding the need to run a web server to serve the specs via HTTP&hellip;

**Comment by marcoscaceres** [comment]
@tripu, ok great. This is good info to so to be able to run this in a CI environment. 
 
However, the reason for me requesting that I be able to POST a payload is that most Editors are not going to be running command line tools. 

My idea was to POST the document to a W3C Server, and have Specberus either send me back a page that lists the errors, or JSON, from which I can present the errors within ReSpec. 

Does the above make sense?
