### ISSUE TITLE
Bug in rules: No mailing list link

### ISSUE THREAD

**Issue by svgeesus** [w3c/specberus#726]
Pubrules check fails with 

**Error** No mailing list link.

however, the actual requirement in pubrules is

> It must include a _public archived place_ to send comments to. 
https://www.w3.org/pubrules/doc/rules?profile=CR#mailingListName

As with many modern W3C documents, **GitHub issues** are preferred for comments. The SOTD includes a link to the relevant GitHub issues page, and also a link to the mailing list which archives those comments. So this is a _public archived place_.

However, pubrules checker is looking for a _mailto_ link, it seems. That is an error in the checker.

Found [while checking `https://www.w3.org/TR/2018/CR-selectors-3-20180130/`](https://www.w3.org/pubrules/?url=https%3A%2F%2Fwww.w3.org%2FTR%2F2018%2FCR-selectors-3-20180130%2F&profile=CR&validation=simple-validation&noRecTrack=false&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004).

**Comment by tripu** [comment]
The problem is that the link is expected to match this regex:

https://github.com/w3c/specberus/blob/0063f13e357ca9f7054085a3df795146f937b1ec/lib/rules/sotd/mailing-list.js#L37

But that spec links to `https://github.com/w3c/csswg-drafts/labels/selectors-3`, which doesn't match.

But I agree that this is confusing: the rule should be clearer and be shown [among the rest](https://www.w3.org/pubrules/doc/rules?profile=CR). I'll submit a PR for that.

In any case, shall we be more flexible with that regex, and accept a link to specific labels, like what this spec is doing, @deniak @plehegar?

**Comment by deniak** [comment]
I wonder if https://github.com/w3c/csswg-drafts/labels/selectors-3 is equivalent to https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Aselectors-3

In the second link, removing `is:issue` from the filters does redirect to the first link. 
If both links are equivalent, then :+1: to extend the regex.

**Comment by tripu** [comment]
Even better: since `https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Aselectors-3` matches the current regex, we can leave it as it is, and specs trying to be more detailed about what labels to use when filing issues (like this one mentioned by @svgeesus here) can use a link that one.

In fact, even an issue &ldquo;template&rdquo; (one pre-populated with title, description and/or labels) satisfies the regex. Example:

[`https://github.com/w3c/specberus/issues/new?title=Foo%20bar&body=Blah%20blah%20blah&labels=bug,security`](https://github.com/w3c/specberus/issues/new?title=Foo%20bar&body=Blah%20blah%20blah&labels=bug,security)

I'd say we leave the regex as it is, since there are these other ways for groups to be more granular when pointing readers to places where they can file new issues&nbsp;&mdash;&nbsp;and they are supported already.

**Comment by svgeesus** [comment]
Okay, but then if people use the simple issues link that GitHub gives you, the error should be more informative, and include the type of issues link that the checker accepts.

**Comment by tripu** [comment]
The &ldquo;simple issues link&rdquo; is `https://github.com/<USER_OR_ORG>/<REPO_NAME>/issues[/]`, right? That one is supported already.

**Comment by tripu** [comment]
After #727, the error message will be clearer, and the rule description will be:

> It **must** include a public archived place to send comments to. (GitHub repository issue links are expected to be of the form `https://github.com/<USER_OR_ORG>/<REPO_NAME>/issues[/…]`.)

, which I think covers all the use cases discussed here (but your spec will have to link to a specific label with a URL like `https://github.com/w3c/csswg-drafts/issues?q=is%3Aopen+is%3Aissue+label%3Aselectors-3` instead of `https://github.com/w3c/csswg-drafts/labels/selectors-3`).
