### ISSUE TITLE
Should we include subtitles in the title?

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#838]
@plehegar, following https://github.com/w3c/respec/issues/2353, should we include the subtitle (if provided) when fetching the title? So far, only a few specs are making use of that `subtitle` but it seems to be useful.

I'll be fine updating the rule that extract the title but we need to agree on a selector. Respec add a `<h2 id=subtitle class=subtitle>` right after the `<h1>` but I don't know if bikeshed has that feature as well.

/cc @andrea-perego @marcoscaceres

**Comment by tabatkins** [comment]
Nearly all W3C specs make use of `<h2 id=subtitle>` to contain the spec status and publication date. This includes the spec in question in <https://github.com/w3c/respec/issues/2353>.

This information isn't useful to include in titles in SpecRef.

**Comment by marcoscaceres** [comment]
Hmm... not with ReSpec specs it seems:
https://w3c.github.io/manifest/?specStatus=WD

Seems we don't add anything. But I agree, if `id=subtitle` is already mostly holding spec status and pub date, then it would mean republishing everything or finding a new id.

**Comment by andrea-perego** [comment]
Sorry, @marcoscaceres & @tabatkins , but I don't see any `id` attribute in the `h2` carrying document status and publishing date.

As far as I know, `<h2 id="subtitle">` is used only to display the value of the `subtitle` field in `config.js`  - and this field can carry information to be added in a bib entry.

The specific TR I was referring to in https://github.com/w3c/respec/issues/2353 is

https://w3c.github.io/dxwg/dcat/

In a previous draft, the string `Version 2` was in the `subtitle` field - we have now moved it to the actual title waiting to see how and whether this issue will be addressed.

If the decision is to keep things as they are now, then some warning should be included in the ReSpec guidelines to make editors aware that things like version numbers and whatever should show up in SpecRef entries must be included in the title itself.

**Comment by tabatkins** [comment]
Yeah, I was misreading. ReSpec uses a plain `<h2>` for the status/date, and a preceding `<h2 id=subtitle class=subtitle>` when you explicitly give a subtitle.

Separately, all of the W3C Bikeshed boilerplates use an `<h2 id=subtitle>` for the status/date. (Not for any particular reasons, I apparently just thought it was important for those headings to have IDs?)

> In a previous draft, the string Version 2 was in the subtitle field - we have now moved it to the actual title waiting to see how and whether this issue will be addressed.

Oh, phew, thanks for making this clear, I was confused because your link appeared to have a perfectly good title. ^_^

**Comment by burnburn** [comment]
Or perhaps the (first/last) `<h2>` *without* id `subtitle` should be used for the profile, since it is likely *not* to be providing a subtitle?  Only in the case where multiple `<h2>`s exist, of course, as you describe.

Thus, for any existing spec with only one `<h2>`, containing `subtitle`, nothing will change, but for those who wish to explicitly identify a subtitle they can use the id in an intuitive way by moving the profile info into another `<h2>` without that id.

**Comment by plehegar** [comment]
I note that https://www.w3.org/TR/pointerevents3/ has 2 H2 elements and doesn't make pubrules choke.

I support with the first `<h2>` without @id `subtitle` .

**Comment by jennyliang220** [comment]
https://www.w3.org/TR/2021/WD-css-cascade-5-20210317/ this is a bikeshed document, the `<h2>` with @id subtitle is used for **W3C Working Draft, 17 March 2021 (profile and date)**. 

> I support with the first `<h2>` without @id subtitle .

@plehegar , if we apply this, we need to ask @tabatkins to upgrade bikeshed.

**Comment by jennyliang220** [comment]
> Currently pubrules chokes for DID document

This was a bug and was fixed in https://github.com/w3c/specberus/pull/1185/, but now pubrule is looking into every `<h2>` to identify profile&date, it's better for us to give an id to the target h2, e.g `<h2 id="profile-and-date">`. @plehegar 

@tabatkins can you remove `id='subtitle'` for profile&date element? 

following code comes from [DID](https://www.w3.org/TR/2021/WD-css-cascade-5-20210317/), a bikeshed document.
```
<h1 class="p-name no-ref" id="title">CSS Cascading and Inheritance Level 5</h1>
<h2 class="no-num no-toc no-ref heading settled" id="subtitle">
    <span class="content">W3C Working Draft, <time class="dt-updated" datetime="2021-03-17">17 March 2021</time></span>
</h2>
```

**Comment by tabatkins** [comment]
Ahahaha, okay, I remember why I added `id=subtitle` to the boilerplates now - without it, Bikeshed complains that you have a heading without an ID, and autogenerates one from the text content. ^_^

Is it okay to switch to `id=profile-and-date` or something? Otherwise I'd have to special-case the heading handling, which is definitely doable, just unfortunate.

**Comment by jennyliang220** [comment]
> Is it okay to switch to id=profile-and-date or something?

Hi @tabatkins, removing `id=subtitle` for **W3C Working Draft, 17 March 2021** will make the document consistent. And yes, `id=profile-and-date` will work. Please ping me when it's done, and I'll update the code.

**Comment by tabatkins** [comment]
All right, I changed the ID and pushed a new version of Bikeshed. Version 2.4.0 has the new code.

**Comment by jennyliang220** [comment]
hi @tabatkins, did you deploy the new version of bikeshed? Pubrules needs to be published after bikeshed.

I tried https://api.csswg.org/bikeshed/ with [css-box-4 .bs document](https://raw.githubusercontent.com/w3c/csswg-drafts/main/css-box-4/Overview.bs) document, and it's using the old version `Bikeshed version c5fd42b86, updated Mon Apr 5 16:27:33 2021 -0700`.  So the id still has `id="subtitle"`.

**Comment by tabatkins** [comment]
I'm poking @plinss to see what's up with that; the server should be listening for commits to the repository, which means it should have been picking up several commits since Apr 5.

That said, if you can run `pip install bikeshed`, you'll get a local install which is up-to-date.

**Comment by plinss** [comment]
There was a db glitch last night, everything should be synced now
