### ISSUE TITLE
Recursive validation is broken again

### ISSUE THREAD

**Issue by gsnedders** [w3c/specberus#870]
e.g. we'd expect https://drafts.csswg.org/css2/ to throw out a load of validation errors; it doesn't

**Comment by jennyliang220** [comment]
Pubrules failed to check https://drafts.csswg.org/css2/ is because this document is **not a valid TR document**, it's an editor's draft. Some [required element](https://github.com/w3c/specberus/blob/60c1ce83269f648d324d080047e6480a80fcfdf6/lib/rules/sotd/supersedable.js#L27) for TR doesn't exist in this editor's draft. 
To make pubrules more robust, elements should be checked before use: https://github.com/w3c/specberus/pull/975/files
