### ISSUE TITLE
"Minimal CR end date not found" message should be more explicit

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#871]
When checking a CR, some people complained that it was not able to find the CR end date while it was actually in the SotD.
The minimal review end date is at least 28 days starting from the publication date.
If the period found is less that 28 days, the error should say so and not simply "end date not found".

**Comment by jennyliang220** [comment]
## Discussion: how to find date for CR feedback due date:

### Now in the code:
https://github.com/w3c/specberus/blob/2ab984ac855af575c1fb139dd630401d4cadcd64/lib/validator.js#L318-L322

### Paragraph regarding CR feedback date:

|document|link| paragraph
|----|----|----|
|Early doc 7 years|https://www.w3.org/TR/2013/CR-css3-conditional-20130404/| The specification will remain Candidate Recommendation at least until **2 October 2013**.
|5 years|https://www.w3.org/TR/2015/CR-css-variables-1-20151203/|This document will remain a Candidate Recommendation at least until **1 June 2016** in order to ensure the opportunity for wide review.|
|2 years|https://www.w3.org/TR/2018/CR-encoding-20180327/|This document will remain a Candidate Recommendation at least until **27 May 2018** in order to ensure the opportunity for wide review.|
|2 years|https://www.w3.org/TR/2018/CR-css-flexbox-1-20181119/|This document will remain a Candidate Recommendation at least until **19 December 2018** in order to ensure the opportunity for wide review|
|New doc|https://www.w3.org/TR/2020/CR-json-ld11-api-20200417/|This Candidate Recommendation is expected to advance to Proposed Recommendation no earlier than **03 April 2020**.

Suggestion: we can use `at least until  + date` or `no earlier than + date` to narrow down the dates.
