### ISSUE TITLE
Profile auto fails for member submission

### ISSUE THREAD

**Issue by deniak** [w3c/specberus#969]
When checking https://www.w3.org/Submission/2020/SUBM-prism-20200910/ with the profile `auto`, specberus gets stuck somewhere

**Comment by jennyliang220** [comment]
It got stuck because 11 of 12 checks are done, lib/validator.js line 68 never achieved.

https://github.com/w3c/specberus/blob/69c0b15a85d2ee584c2a01b19b80ad4c6bd59174/lib/validator.js#L60-L69

The one rule got stuck is patent-policy.js, when `deliverers.length === 0`, no `done()` was called. 

https://github.com/w3c/specberus/blob/69c0b15a85d2ee584c2a01b19b80ad4c6bd59174/lib/rules/metadata/patent-policy.js#L13-L31
